package com.swifttrack.enums;

public enum UserType {
    TENANT_USER, DRIVER_USER, PROVIDER_USER, ADMIN_USER, TENANT_ADMIN, SYSTEM_ADMIN, SYSTEM_USER, SUPER_ADMIN,
    TENANT_DRIVER, TENANT_MANAGER, TENANT_STAFF

}
