spring:
  application:
    name: GateWay
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOriginPatterns:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/authservice/**
          filters:
            - StripPrefix=1
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
